type Movie {
    _id:ID!
    title:String!
    genre: String!
    year: Int!
    director: String!
    urlImage: String
    urlMovie: String
    description: String!
}

input MovieInput {
    title:String!
    genre: String!
    year: Int!
    director: String!
    urlImage: String
    urlMovie: String
    description: String!
}

type Query {
    movies: [Movie!]!
    movie(id:String): Movie!
    getMovieByTitle(title:String): Movie!
    getMovieByGenre(genre:String): [Movie!]!
    getMovieByYear(year:Int): [Movie!]!
}

type Mutation {
   createMovie(data: MovieInput!): Movie! 
   updateMovie(id: ID!, data: MovieInput!): Movie!
   deleteMovie(id: ID!): Boolean
}