 input MovieInput {
    id: ID
    title: String
    genre: String
    year: Int
    popularity: Float
    director: String
    urlImage: String
    backdrop_path: String
    urlMovie: String
    description: String
  }

   input ActorInput {
    id: ID
    movieID: Int
    adult: Boolean
    gender: Int
    known_for_department: String
    name: String
    original_name: String
    popularity: Float
    profile_path: String
    cast_id: Int
    character: String
    credit_id: String
    order: Int
  }

  input filterMovies {
    genre: String
    title: String
    year: Int
  }
